name: BetterRules
version: 1.0.0
main: ByEvidencias\Main
api: 5.0.0
author: ByEvidencias 
description: "Rules UI"
website: https://github.com/b4daz/BetterRules

permissions:
  betterrules.cmd:
    description: "Allows the user to use /rules"
    default: true
    
